// Every part omapad draws a control tile from, as path data.
//
// GENERATED by assets/generate.py from assets/shapes/*.svg - do not edit.
// Redraw the shape or change the table there and run the script again.
//
// **Not a font.** The TrueType half of the generator exists to turn letters
// into outlines so they can be punched out of a button; nothing here has a
// letter in it, so nothing here goes near it. What is generated is the same
// path data with that step skipped.
//
// Only the furniture is here - what does not depend on the value. The arc
// that follows a number, the dot that follows a thumb and the travel of a
// knob are geometry, and geometry is the panel's: a shape parameterised by a
// number cannot be drawn once. It is the same split BadgeArt already makes
// between a button and the label set into it.
//
// Coordinates are in the shape's own units (`w` x `h`); a Shape scales them.
// Painted by BadgeArt, like any other drawn entry.
import QtQuick

QtObject {
  id: art

  readonly property var controls: ({
    "chev:left": { w: 32, h: 32, shape: "M21 5L10 16L21 27L25 23L18 16L25 9Z" },
    "chev:right": { w: 32, h: 32, shape: "M11 5L22 16L11 27L7 23L14 16L7 9Z" },
    "dial:face": { w: 40, h: 40, shape: "M2 20A18 18 0 0 1 38 20A18 18 0 0 1 2 20ZM5 20A15 15 0 0 0 35 20A15 15 0 0 0 5 20Z" },
    "dial:thumb": { w: 40, h: 40, shape: "M17 20A3 3 0 1 0 23 20A3 3 0 1 0 17 20Z" },
    "dial:ticks": { w: 40, h: 40, shape: "M19 6H21V10H19ZM19 30H21V34H19ZM6 19H10V21H6ZM30 19H34V21H30Z" },
    "media:next": { w: 32, h: 32, shape: "M8 7L20 16L8 25ZM22 7H25V25H22Z" },
    "media:pause": { w: 32, h: 32, shape: "M10 7H15V25H10ZM17 7H22V25H17Z" },
    "media:play": { w: 32, h: 32, shape: "M10 7L25 16L10 25Z" },
    "media:prev": { w: 32, h: 32, shape: "M24 7L12 16L24 25ZM7 7H10V25H7Z" },
    "switch:body": { w: 64, h: 40, shape: "M16 4H48A16 16 0 0 1 48 36H16A16 16 0 0 1 16 4Z" },
    "switch:knob": { w: 40, h: 40, shape: "M6 20A14 14 0 1 0 34 20A14 14 0 1 0 6 20Z" },
    "tile:grip": { w: 32, h: 32, shape: "M10 9A2 2 0 1 0 14 9A2 2 0 1 0 10 9ZM18 9A2 2 0 1 0 22 9A2 2 0 1 0 18 9ZM10 16A2 2 0 1 0 14 16A2 2 0 1 0 10 16ZM18 16A2 2 0 1 0 22 16A2 2 0 1 0 18 16ZM10 23A2 2 0 1 0 14 23A2 2 0 1 0 10 23ZM18 23A2 2 0 1 0 22 23A2 2 0 1 0 18 23Z" }
  })

  // One part, or null where that family has no such part - a caller that
  // asked for one is a control shipped with a hole in it, which
  // tests/test_assets.py is what notices.
  function find(family, name) {
    var found = art.controls[family + ":" + name]
    return found !== undefined ? found : null
  }
}
