// The ground a menu tile is drawn on, one outline per state.
//
// GENERATED by assets/generate.py from assets/shapes/ground-*.svg - do not
// edit. Redraw a corner or change the table there and run the script again.
//
// **The corner is drawn art; the edges between the corners are a number.** A
// tile is `w` cells by `h` rows, and a shape scaled by one factor cannot be a
// rectangle of any aspect - which is the rule the slider's track and the
// dial's shaded zone are not drawn under. A corner is not parameterised by
// anything, though, and a straight edge does not have to be drawn to be
// right, so a ground is the one and the other: the same quarter set at four
// corners with lines run between them.
//
// Why at all, when a Rectangle has a radius: a radius is the only outline a
// Rectangle has, and the states of a tile want more than one. A theme whose
// accent sits close to its surface leaves a selection to the border alone,
// and the border is the thinnest thing on the tile.
//
// The corner is rotated into its four places rather than mirrored, because a
// rotation carries an arc's sweep flag through unchanged and a mirror would
// have to flip every one of them.
import QtQuick

QtObject {
  id: art

  readonly property var grounds: ({
    "carried": { corner: 16, tl: [["l", 0, -10], ["l", 6, 0], ["l", 0, -6], ["l", 10, 0]], tr: [["l", 10, 0], ["l", 0, 6], ["l", 6, 0], ["l", 0, 10]], br: [["l", 0, 10], ["l", -6, 0], ["l", 0, 6], ["l", -10, 0]], bl: [["l", -10, 0], ["l", 0, -6], ["l", -6, 0], ["l", 0, -10]] },
    "plain": { corner: 16, tl: [["a", 16, 16, 0, 0, 1, 16, -16]], tr: [["a", 16, 16, 90, 0, 1, 16, 16]], br: [["a", 16, 16, 180, 0, 1, -16, 16]], bl: [["a", 16, 16, 270, 0, 1, -16, -16]] },
    "selected": { corner: 16, tl: [["l", 4, -12], ["l", 12, -4]], tr: [["l", 12, 4], ["l", 4, 12]], br: [["l", -4, 12], ["l", -12, 4]], bl: [["l", -12, -4], ["l", -4, -12]] }
  })

  // An arc's rotation and its two flags are not lengths, so they are the
  // three arguments a corner being scaled down leaves alone.
  function scaled(commands, factor) {
    var out = ""
    for (var i = 0; i < commands.length; i++) {
      var command = commands[i]
      out += command[0]
      for (var j = 1; j < command.length; j++) {
        var flag = command[0] === "a" && j >= 3 && j <= 5
        out += (j > 1 ? " " : "") + (flag ? command[j] : command[j] * factor)
      }
    }
    return out
  }

  // The outline of a tile `w` by `h` with `corner` pixels of drawing in each
  // corner. Clockwise from where the left edge runs into the top left corner,
  // so the fill rule sees one contour wound one way whatever the state is.
  //
  // The corner shrinks rather than the tile: four corners of a tile narrower
  // than two of them would overlap, and an outline that crosses itself is
  // painted with a hole in it.
  function ground(name, w, h, corner) {
    var found = art.grounds[name]
    if (found === undefined || w <= 0 || h <= 0) return ""
    var c = Math.min(corner, w / 2, h / 2)
    var factor = c / found.corner
    return "M0 " + c + art.scaled(found.tl, factor)
      + "L" + (w - c) + " 0" + art.scaled(found.tr, factor)
      + "L" + w + " " + (h - c) + art.scaled(found.br, factor)
      + "L" + c + " " + h + art.scaled(found.bl, factor)
      + "Z"
  }
}
